# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\"\x1d\n\rStreamReqData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\rStreamResData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t28\n\x07Greeter\x12-\n\tGetStream\x12\x0e.StreamReqData\x1a\x0e.StreamResData0\x01\x42\nZ\x08../protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _STREAMREQDATA._serialized_start=16
  _STREAMREQDATA._serialized_end=45
  _STREAMRESDATA._serialized_start=47
  _STREAMRESDATA._serialized_end=76
  _GREETER._serialized_start=78
  _GREETER._serialized_end=134
# @@protoc_insertion_point(module_scope)
